site_name: Learning @ RENware Software Systems
site_author: 'Petre Iordanescu, RENware Software Systems'
copyright: 'Copyright (c) RENware Software Systems'


nav:
    - Home: 'index.md'
    - Learning catalog: 'learning_catalog.md'
    - About platform: 'about.md'
    - RENware Software Systems: 'http://www.renware.eu'
    #FIXME_chk_ok_if_only_cource_catalog_? - Full TLP Manual (PDF): 'pdfs/print_page.html/print_page.pdf'



markdown_extensions:
    - admonition
    - tables
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences: #NOTE: [petre iordanescu]: is very important to respect syntax ref `-` character at beginning of items (otherwise not right JSON result !)
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true


#NOTE required to render `mermaid` diagrams
extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - extra-loader.js



plugins:
    - search
    - include-markdown
    # - pdf-export # this version does not render mermaid in PDF docs
    #FIXME_check_if_needed - print-site: #NOTE: put print-site to the bottom of the plugins that may might alter your site navigation (affect order of sections in generated HTML)
        #FIXME_check_if_needed add_to_navigation: true
        #FIXME_check_if_needed print_page_title: 'Full ArtK Manual'
        #FIXME_check_if_needed add_full_urls: true
        #FIXME_check_if_needed add_table_of_contents: true
    - pdf-with-js:
        enable: true



#NOTE provide material theme
theme:
    logo: pictures/REN_TLP_logo.png ##FIXME set right learning @ renware logo
    name: material
    features:
        - navigation.tabs #NOTE level 2 on left navigation side bar, level 1 on top navigation bar
        - navigation.tracking
        - navigation.tabs.sticky
        - navigation.path
        - toc.integrate #NOTE integrate TOC in left navbar
        #- navigation.footer #NOTE do not enable this. It will show "Next & Prev" links on footer, useless for this portal...
    palette:
        primary: deep purple # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/ for other color options
    icon:
        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left



#NOTE or can use readthedocs theme but should check mermaid diagrams
# theme: readthedocs



#NOTE directory where start to search or markdown sources
docs_dir: './doc_src'


#NOTE root directory where to be generated portal (should be `./static_portal`)
site_dir: './static_portal'



#NOTE other useful configurations
use_directory_urls: false # allow link between pages to work properly when used as OFFLINE deployment (ie, static site an "callable" as `file:///...`)


